apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bergren.lam@icloud.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: 
        dnsNames:
        - '*.linshibin.com'
      dns01:
        webhook:
          config:
            accessKeyId: LTAI4FnnHGqj86hphKJtZE85
            accessKeySecretRef:
              key: accessKeySecret
              name: alidns-credentials
            regionId: "cn-shenzhen"
            ttl: 600
          groupName: certmanager.webhook.alidns
          solverName: alidns
